package org.osm2world.world.data;

import static java.util.Objects.requireNonNullElse;
import static org.osm2world.scene.mesh.MeshWithMetadata.MeshMetadata;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

import javax.annotation.Nullable;

import org.osm2world.math.VectorXZ;
import org.osm2world.output.CommonTarget;
import org.osm2world.scene.mesh.*;
import org.osm2world.scene.model.ModelInstance;
import org.osm2world.world.attachment.AttachmentSurface;

/**
 * a model which is generated by code during runtime,
 * rather than being loaded as a static asset
 */
public interface ProceduralWorldObject extends WorldObject {

	void buildMeshesAndModels(Target target);

	class Target implements CommonTarget {

		protected final List<MeshWithMetadata> meshes = new ArrayList<>();
		protected final List<ModelInstance> subModels = new ArrayList<>();
		protected final List<AttachmentSurface> attachmentSurfaces = new ArrayList<>();

		private @Nullable LODRange currentLodRange = null;
		private List<String> currentAttachmentTypes = List.of();
		private @Nullable WorldObject currentAttachmentObject = null;
		private @Nullable Function<VectorXZ, Double> currentBaseEleFunction = null;
		private Map<String, Object> currentMetadata = Map.of();

		public @Nullable LODRange getCurrentLodRange() {
			return currentLodRange;
		}

		public void setCurrentLodRange(@Nullable LODRange lodRange) {
			this.currentLodRange = lodRange;
		}

		public void setCurrentLodRange(LevelOfDetail minLod, LevelOfDetail maxLod) {
			this.setCurrentLodRange(new LODRange(minLod, maxLod));
		}

		public void setCurrentAttachmentTypes(WorldObject worldObject, String... attachmentTypes) {
			setCurrentAttachmentTypes(worldObject, null, attachmentTypes);
		}

		public void setCurrentAttachmentTypes(WorldObject worldObject,
				@Nullable Function<VectorXZ, Double> baseEleFunction, String... attachmentTypes) {
			this.currentBaseEleFunction = baseEleFunction;
			this.currentAttachmentObject = worldObject;
			this.currentAttachmentTypes = List.of(attachmentTypes);
		}

		/** sets metadata for meshes which are drawn after this call */
		public void setCurrentMetadata(@Nullable Map<String, Object> metadata) {
			this.currentMetadata = requireNonNullElse(metadata, Map.of());
		}

		@Override
		public void drawMesh(Mesh mesh) {

			if (currentLodRange != null) {
				mesh = new Mesh(mesh.geometry, mesh.material, currentLodRange.min(), currentLodRange.max());
			}

			MeshMetadata metadata = new MeshMetadata(null, null, currentMetadata);

			meshes.add(new MeshWithMetadata(mesh, metadata));

			if (!currentAttachmentTypes.isEmpty()) {
				attachmentSurfaces.add(AttachmentSurface.fromMeshes(currentAttachmentTypes, currentAttachmentObject, List.of(mesh), currentBaseEleFunction));
			}

		}

		public void addSubModel(ModelInstance subModel) {
			subModels.add(subModel);
		}

		public List<Mesh> meshes() {
			return meshes.stream().map(MeshOrMeshWithMetadata::asMesh).toList();
		}

		List<MeshWithMetadata> meshesWithMetadata(ProceduralWorldObject worldObject) {
			List<MeshWithMetadata> result = new ArrayList<>(meshes.size());
			for (MeshWithMetadata m : meshes) {
				var metadata = new MeshMetadata(worldObject.getPrimaryMapElement().getElementWithId(),
						worldObject.getClass(), m.metadata().extraProperties());
				result.add(new MeshWithMetadata(m.mesh(), metadata));
			}
			return result;
		}

	}

	@Override
	default List<? extends MeshOrMeshWithMetadata> buildMeshes() {
		var target = new Target();
		buildMeshesAndModels(target);
		return target.meshesWithMetadata(this);
	}

	@Override
	default List<ModelInstance> getSubModels() {
		var target = new Target();
		buildMeshesAndModels(target);
		return target.subModels;
	}

	@Override
	default Collection<AttachmentSurface> getAttachmentSurfaces() {
		var target = new Target();
		buildMeshesAndModels(target);
		return target.attachmentSurfaces;
	}
}
